name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test shop app 
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install requirements
      run: yarn install
    - name: Run tests and collect coverage
      run: yarn test:coverage
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/lcov.info

